<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Collecte extends Model
{
    use HasFactory;

    protected $fillable = [
       'age',
       'sexe',
       'pays',
       'ville',
       'symp',   
       'case1',
       'case2',
       'case3',
       'case4',
       'case5',
       'case6',
       'case7',
       'case8',
       'case9',
       'case10',
       'case11',
       'case12',
       'case13',
       'case14',
       'case15',
       'case16',
       'case17',
       'case18',
       'case19',
       'case20',
       'case21',
       'case22',
       'case23',
       'case24',
       'case25',

       'case26',
       'case27',
       'case28',
       'case29',
       'case30',
       'case31',
       'case32',
       'case33',
       'case34',
       'case35',
       'case36',
       'case37',
       'case38',
       'case39',
       'case40',
       'case41',
       'case42',
       'case43',
       'case44',
       'case45',
       'case46',
       'case47',
       'case48',
       'case49',
       'case50',
       'intensite1',
       'intensite2',
       'intensite3',
       'intensite4',
       'intensite5',
       'intensite6',
       'intensite7',
       'intensite8',
       'intensite9',
       'intensite10',
    ];
}
